version: 1
formatters:
  brief:
    format: '%(asctime)s - [%(levelname)s]: %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    stream: ext://sys.stdout
loggers:
  nestor:
    level: INFO
    handlers: [ console ]
    propagate: false
root:
  level: DEBUG
  handlers: [ console ]